# Generated by Django 3.2.25 on 2025-07-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='drone',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='dronecategory',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='drone',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='dronecategory',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
