# Generated by Django 3.2.25 on 2024-11-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toy',
            options={'ordering': ('-id', 'name')},
        ),
    ]
